spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/tb1
spring.datasource.username=root
spring.datasource.password=debraj@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081




gemini.api.key=AIzaSyCR5I2yHJwVSol69UJ1GRXUxcmmqbwbxR4
# Leave blank to auto-pick from listModels, or set e.g. "models/gemini-1.5-flash-latest"
gemini.model=
